### ISSUE TITLE
No module named 'quantmod.theming'

### ISSUE THREAD

**Issue by snowriverout** [jackwluo/py-quantmod#9]
Hello,
I'm trying to run dash_example_simple.py, but I received the following error message "ModuleNotFoundError: No module named 'quantmod.theming'" . I already tried looking at a previous post regarding the same issue, but wasn't able to figure it out. Can anyone help? Thanks.

**Comment by snowriverout** [comment]
Traceback (most recent call last):
  File "quantmod_demo.py", line 8, in <module>
    import quantmod as qm
  File "~/anaconda3/lib/python3.6/site-packages/quantmod/__init__.py", line 23, in <module>
    from .core import *
  File "~/anaconda3/lib/python3.6/site-packages/quantmod/core.py", line 13, in <module>
    from .chart import Chart
  File "~/anaconda3/lib/python3.6/site-packages/quantmod/chart.py", line 22, in <module>
    from . import factory
  File "~/anaconda3/lib/python3.6/site-packages/quantmod/factory.py", line 14, in <module>
    from .theming.skeleton import SKELETON
ModuleNotFoundError: No module named 'quantmod.theming'

**Comment by hikingyu** [comment]
this is install mistake.I try replace the setup.py and is ok.
setup.py
from setuptools import setup,find_packages


exec (open('quantmod/version.py').read())  # noqa

setup(
    name='quantmod',
    version=__version__,  # noqa
    author='Jack Luo',
    author_email='jackluo@plot.ly',
    description="Powerful financial charting library based on R's Quantmod.",
    long_description=open('README.md').read(),
    license='MIT',
    keywords=['pandas', 'plotly', 'ta-lib', 'data-visualization',
              'data-science', 'quantitative-finance', 'quantitative-trading'],
    packages=find_packages(),
    install_requires=[
        'numpy',
        'pandas',
        'pandas_datareader',
        'plotly'
    ]
)

**Comment by matthewchan15** [comment]
I also get this error....

**Comment by KIC** [comment]
error remains with the mentioned changed setup.py
